# Generated by Django 3.2.21 on 2024-01-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonetician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('official_name', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vowel_str', models.CharField(max_length=2)),
                ('vowel', models.IntegerField()),
                ('path', models.CharField(max_length=100)),
                ('f1', models.IntegerField()),
                ('f2', models.IntegerField()),
                ('f3', models.IntegerField()),
                ('phonetician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_databasecreation.phonetician')),
            ],
        ),
    ]
